export const ENCRYPT_BLOCK_IDENTIFIER = "encrypt";
export const GENERATOR_BLOCK_IDENTIFIER = "encryptgenerator";

export const strings = {
  "enter-password": "Password",
  "repeat-password": "Confirm",
  "enter-password-hint": "Hint",
  "password-placeholder": "Password",
  "hint-placeholder": "Hint",
  "generate-button": "GENERATE",
  "decrypt-button": "DECRYPT",
  "save-button": "SAVE",
  "submit-button": "SUBMIT",
  "passwords-not-matching": "Passwords not matching.",
  "please-enter-passwords": "Please enter passwords.",
  "new-encrypt-block-placeholder": "[Insert text to be encrypted here]",
  "generator-in-read-mode-title": "Encrypt Generator",
  "generator-in-read-mode-div": "(Switch to Edit Mode)",
  "error-password-empty": "",
  "error-incorrect-password": "Incorrect password.",
  "button-lock": "Lock",
  "button-change-password": "Change passsword",
  "button-save": "Save",
  "enter-new-password": "Password",
  "enter-new-hint": "Hint",
  "insert-encryption-block": "Insert encryption block",
  "encrypt-selection": "Encrypt selection",
  "hint": "Hint",
  "mode-single": "Single",
  "mode-group": "Group",
}